name: doing-devops-lab3-stuff

on:
  push:
    branches:
      - main

jobs:
  generate-text-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build the docker image
      run: docker build -t lab3-generating-text .

    - name: Run the docker container
      run: docker run lab3-generating-text

    - name: Copy output.txt back to the repository
      run: cp /output.txt/ $GITHUB_WORKSPACE

    - name: Commit and push generated output.txt
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add output.txt
        git commit -m "Add generated output.txt"
        git push

  push-on-dockerhub:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      run: actions/checkout@v4

    - name: Login on dockerhub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Push image on dockerhub
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: dio05000_lab3-image:latest
